### ISSUE TITLE
Cube building failed at Step 8 with exitCode 2

### ISSUE THREAD

**Issue by butterluo** [KylinOLAP/Kylin#372]
I created a cube following the "Kylin-Cube-Creation-Tutorial".
The fact table is "TEST_KYLIN_FACT". The cube has two dimensions, one is "TEST_KYLIN_FACT.LSTG_FORMAT_NAME" the other is "TEST_CAL_DT.CAL_DT", two measures, ons is "SUM of TEST_KYLIN_FACT.PRICE" the other is "COUNT_DISTINCT of TEST_KYLIN_FACT.SELLER_ID".
But when I built this cube, it failed at step 8 (creation of the HBase table) with exitCode 2.
And I found an exception in kylin_job.log, "IllegalStateException: Split number is 0, no records in cube" .
The version of Kylin I used is 0.6.2.
The exception stack:
java.lang.IllegalStateException: Split number is 0, no records in cube??
        at com.kylinolap.job.hadoop.hbase.CreateHTableJob.getSplits(CreateHTableJob.java:176)
        at com.kylinolap.job.hadoop.hbase.CreateHTableJob.run(CreateHTableJob.java:111)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at com.kylinolap.job.cmd.JavaHadoopCmd.execute(JavaHadoopCmd.java:53)
        at com.kylinolap.job.flow.JobFlowNode.execute(JobFlowNode.java:77)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

Can any one help to solve this problem?

**Comment by lukehan** [comment]
could you please check your hive table's data? looks like there's no data in your hive table
