### ISSUE TITLE
kylin0.7.1 && hadoop2.6.0部署任务调度器出错问题

### ISSUE THREAD

**Issue by zengzhaozheng** [KylinOLAP/Kylin#458]
WARNING: Failed to process JAR [jar:file:/data1/app/hadoop-2.6.0/contrib/capacity-scheduler/*.jar!/] for TLD files
java.io.FileNotFoundException: /data1/app/hadoop-2.6.0/contrib/capacity-scheduler/*.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:153)
        at java.util.jar.JarFile.<init>(JarFile.java:90)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at org.apache.tomcat.util.scan.FileUrlJar.<init>(FileUrlJar.java:41)
        at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:34)
        at org.apache.catalina.startup.TldConfig.tldScanJar(TldConfig.java:485)
        at org.apache.catalina.startup.TldConfig.access$100(TldConfig.java:61)
        at org.apache.catalina.startup.TldConfig$TldJarScannerCallback.scan(TldConfig.java:296)
        at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:258)
        at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:220)
        at org.apache.catalina.startup.TldConfig.execute(TldConfig.java:269)
        at org.apache.catalina.startup.TldConfig.lifecycleEvent(TldConfig.java:565)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5412)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
hadoop2.x contrib文件夹应该是没有的，这个为什么还会用这个文件夹？

**Comment by binmahone** [comment]
The fastest way to get response from our developers is to send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org

**Comment by cqChao03** [comment]
hadoop默认会采用contrib中贡献出来调度策略，可以把hadoop-en.sh中含有contrib的那几行注释掉就可以了

**Comment by lukehan** [comment]
This Github Issues is closed already.

Please open JIRA for any Kylin relative issue: [http://issues.apache.org/jira/browse/KYLIN](http://issues.apache.org/jira/browse/KYLIN) 

or send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org

**Comment by shizl92** [comment]
https://github.com/KylinOLAP/Kylin/issues/458
cqChao03 is right
