### ISSUE TITLE
ERROR when build the sample job.and find the hbase regionserver stoped.we use hadoop fedaration

### ISSUE THREAD

**Issue by leavesgreen** [KylinOLAP/Kylin#467]
see the kylin _job.log
-------------------------
This server is in the failed servers list: hd02.zi/172.16.20.32:60020
Fri Jun 12 01:54:54 PDT 2015, org.apache.hadoop.hbase.client.RpcRetryingCaller@7899f792, org.apache.hadoop.hbase.ipc.RpcClient$FailedServerException: This server is in the failed servers list: hd02.zi/172.16.20.32:60020
Fri Jun 12 01:54:56 PDT 2015, org.apache.hadoop.hbase.client.RpcRetryingCaller@7899f792, java.net.ConnectException: Connection refused
Fri Jun 12 01:55:00 PDT 2015, org.apache.hadoop.hbase.client.RpcRetryingCaller@7899f792, java.net.ConnectException: Connection refused

----------------------
see the hbase region server log.

the hbase regionserver failed when i try to restart, by the following exception.
The coprocessor org.apache.kylin.storage.hbase.coprocessor.endpoint.IIEndpoint threw java.io.IOException: viewfs://zi/
	at org.apache.hadoop.fs.viewfs.InodeTree.<init>(InodeTree.java:338)
	at org.apache.hadoop.fs.viewfs.ViewFileSystem$1.<init>(ViewFileSystem.java:165)
	at org.apache.hadoop.fs.viewfs.ViewFileSystem.initialize(ViewFileSystem.java:165)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2596)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apach

**Comment by lukehan** [comment]
This Github Issues is closed already.

Please open JIRA for any Kylin relative issue: [http://issues.apache.org/jira/browse/KYLIN](http://issues.apache.org/jira/browse/KYLIN) 

or send email to our mail list dev@kylin.incubator.apache.org, and remember to subscribe our mail list via dev-subscribe@kylin.incubator.apache.org
