### ISSUE TITLE
1.5.2.1 hbase1.x IRealizationSegment not found.

### ISSUE THREAD

**Issue by terry19850829** [KylinOLAP/Kylin#478]
I installed kylin with download the package from apache 

http://archive.apache.org/dist/kylin/apache-kylin-1.5.2.1/apache-kylin-1.5.2.1-HBase1.x-bin.tar.gz

when I test with the sample cube and build the cube, when building extract fact table distinct columns  I faced the error below:

> kylin log
2017-10-06 07:01:47.33 - State of Hadoop job: job_1507225231674_0014:ACCEPTED - UNDEFINED
2017-10-06 07:01:57.64 - State of Hadoop job: job_1507225231674_0014:ACCEPTED - UNDEFINED
2017-10-06 07:02:07.77 - State of Hadoop job: job_1507225231674_0014:ACCEPTED - UNDEFINED
2017-10-06 07:02:17.94 - State of Hadoop job: job_1507225231674_0014:ACCEPTED - UNDEFINED
2017-10-06 07:02:27.107 - State of Hadoop job: job_1507225231674_0014:RUNNING - UNDEFINED
2017-10-06 07:02:37.135 - State of Hadoop job: job_1507225231674_0014:RUNNING - UNDEFINED
2017-10-06 07:02:47.149 - State of Hadoop job: job_1507225231674_0014:RUNNING - UNDEFINED
2017-10-06 07:02:57.166 - State of Hadoop job: job_1507225231674_0014:RUNNING - UNDEFINED
2017-10-06 07:03:07.185 - State of Hadoop job: job_1507225231674_0014:RUNNING - UNDEFINED
2017-10-06 07:03:17.202 - State of Hadoop job: job_1507225231674_0014:RUNNING - UNDEFINED
2017-10-06 07:03:27.218 - State of Hadoop job: job_1507225231674_0014:FINISHED - FAILED
no counters for job job_1507225231674_0014

> yarn log
Error: java.lang.ClassNotFoundException: org.apache.kylin.metadata.realization.IRealizationSegment at java.net.URLClassLoader$1.run(URLClassLoader.java:366) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:270) at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134) at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099) at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193) at org.apache.hadoop.mapreduce.task.JobContextImpl.getMapperClass(JobContextImpl.java:186) at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:745) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:415) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

My hbase version is 1.1.5
hadoop 2.7.2
hive 1.1.5 

Any ideas ?

**Comment by terry19850829** [comment]
Changing the kylin version to 1.6.0 , just worked. This maybe a bug of  apache-kylin-1.5.2.1-HBase1.x-bin.tar.gz

**Comment by liyang-gmt8** [comment]
Please post errors/findings to Apache Kylin mailing list.

http://kylin.apache.org/community/

**Comment by terry19850829** [comment]
ok
