### ISSUE TITLE
Build cube with spark

### ISSUE THREAD

**Issue by jetliu1711** [KylinOLAP/Kylin#481]
OS command error exit with return code: 1, error message: 18/07/13 17:42:29 INFO yarn.Client: Requesting a new application from cluster with 40 NodeManagers
18/07/13 17:42:30 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (106496 MB per container)
18/07/13 17:42:30 INFO yarn.Client: Will allocate AM container, with 1408 MB memory including 384 MB overhead
18/07/13 17:42:30 INFO yarn.Client: Setting up container launch context for our AM
18/07/13 17:42:30 INFO yarn.Client: Setting up the launch environment for our AM container
18/07/13 17:42:30 INFO yarn.Client: Preparing resources for our AM container
18/07/13 17:42:31 WARN yarn.Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
18/07/13 17:42:33 INFO yarn.Client: Uploading resource file:/tmp/spark-c6a78297-b6e3-4cda-b37e-bc4faee88de4/__spark_libs__7388482831237176946.zip -> hdfs://moji-online/user/hadoop/.sparkStaging/application_1530818959513_7528/__spark_libs__7388482831237176946.zip
18/07/13 17:42:34 INFO yarn.Client: Uploading resource file:/data1/demo/soft/kylin/apache-kylin-2.4.0-bin-hbase1x/lib/kylin-job-2.4.0.jar -> hdfs://moji-online/user/hadoop/.sparkStaging/application_1530818959513_7528/kylin-job-2.4.0.jar
18/07/13 17:42:34 WARN yarn.Client: Same path resource file:/data1/demo/soft/kylin/apache-kylin-2.4.0-bin-hbase1x/lib/kylin-job-2.4.0.jar added multiple times to distributed cache.
18/07/13 17:42:34 INFO yarn.Client: Uploading resource file:/tmp/spark-c6a78297-b6e3-4cda-b37e-bc4faee88de4/__spark_conf__6167968862278016867.zip -> hdfs://moji-online/user/hadoop/.sparkStaging/application_1530818959513_7528/__spark_conf__.zip
18/07/13 17:42:34 WARN yarn.Client: spark.yarn.am.extraJavaOptions will not take effect in cluster mode
18/07/13 17:42:34 INFO spark.SecurityManager: Changing view acls to: hadoop
18/07/13 17:42:34 INFO spark.SecurityManager: Changing modify acls to: hadoop
18/07/13 17:42:34 INFO spark.SecurityManager: Changing view acls groups to: 
18/07/13 17:42:34 INFO spark.SecurityManager: Changing modify acls groups to: 
18/07/13 17:42:34 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hadoop); groups with view permissions: Set(); users  with modify permissions: Set(hadoop); groups with modify permissions: Set()
18/07/13 17:42:34 INFO yarn.Client: Submitting application application_1530818959513_7528 to ResourceManager
18/07/13 17:42:34 INFO impl.YarnClientImpl: Submitted application application_1530818959513_7528
18/07/13 17:42:35 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:42:35 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.default
	 start time: 1531474954532
	 final status: UNDEFINED
	 tracking URL: http://master080:8088/proxy/application_1530818959513_7528/
	 user: hadoop
18/07/13 17:42:36 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:42:37 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:42:38 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:42:39 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:42:40 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:42:41 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:41 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: 172.16.19.60
	 ApplicationMaster RPC port: 0
	 queue: root.default
	 start time: 1531474954532
	 final status: UNDEFINED
	 tracking URL: http://master080:8088/proxy/application_1530818959513_7528/
	 user: hadoop
18/07/13 17:42:42 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:43 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:44 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:45 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:46 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:47 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:48 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:49 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:50 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:51 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:52 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:53 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:54 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:55 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:56 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:57 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:58 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:42:59 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:00 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:01 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:02 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:02 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.default
	 start time: 1531474954532
	 final status: UNDEFINED
	 tracking URL: http://master080:8088/proxy/application_1530818959513_7528/
	 user: hadoop
18/07/13 17:43:03 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:04 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:05 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:06 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:07 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:08 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:09 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:10 INFO yarn.Client: Application report for application_1530818959513_7528 (state: ACCEPTED)
18/07/13 17:43:11 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:11 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: 172.16.19.88
	 ApplicationMaster RPC port: 0
	 queue: root.default
	 start time: 1531474954532
	 final status: UNDEFINED
	 tracking URL: http://master080:8088/proxy/application_1530818959513_7528/
	 user: hadoop
18/07/13 17:43:12 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:13 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:14 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:15 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:16 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:17 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:18 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:19 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:20 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:21 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:22 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:23 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:24 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:25 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:26 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:27 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:28 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:29 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:30 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:31 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:32 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:33 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:34 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:35 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:36 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:37 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:38 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:39 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:40 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:41 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:42 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:43 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:44 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:45 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:46 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:47 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:48 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:49 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:50 INFO yarn.Client: Application report for application_1530818959513_7528 (state: RUNNING)
18/07/13 17:43:51 INFO yarn.Client: Application report for application_1530818959513_7528 (state: FINISHED)
18/07/13 17:43:51 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: User class threw exception: java.lang.RuntimeException: error execute org.apache.kylin.engine.spark.SparkCubingByLayer
	 ApplicationMaster host: 172.16.19.88
	 ApplicationMaster RPC port: 0
	 queue: root.default
	 start time: 1531474954532
	 final status: FAILED
	 tracking URL: http://master080:8088/proxy/application_1530818959513_7528/
	 user: hadoop
Exception in thread "main" org.apache.spark.SparkException: Application application_1530818959513_7528 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1180)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1226)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:744)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/07/13 17:43:51 INFO util.ShutdownHookManager: Shutdown hook called
18/07/13 17:43:51 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-c6a78297-b6e3-4cda-b37e-bc4faee88de4
The command is: 
export HADOOP_CONF_DIR=/data1/demo/soft/hadoop-2.7.3/etc/hadoop && /data1/demo/soft/kylin/apache-kylin-2.4.0-bin-hbase1x/spark/bin/spark-submit --class org.apache.kylin.common.util.SparkEntry  --conf spark.executor.instances=4  --conf spark.yarn.queue=default  --conf spark.yarn.am.extraJavaOptions=-Dhdp.version=current  --conf spark.history.fs.logDirectory=hdfs:///kylin/spark-history  --conf spark.driver.extraJavaOptions=-Dhdp.version=current  --conf spark.master=yarn  --conf spark.executor.extraJavaOptions=-Dhdp.version=current  --conf spark.hadoop.yarn.timeline-service.enabled=false  --conf spark.executor.memory=8G  --conf spark.eventLog.enabled=true  --conf spark.eventLog.dir=hdfs:///kylin/spark-history  --conf spark.executor.cores=3  --conf spark.submit.deployMode=cluster --jars /data1/demo/soft/kylin/apache-kylin-2.4.0-bin-hbase1x/lib/kylin-job-2.4.0.jar /data1/demo/soft/kylin/apache-kylin-2.4.0-bin-hbase1x/lib/kylin-job-2.4.0.jar -className org.apache.kylin.engine.spark.SparkCubingByLayer -hiveTable default.kylin_intermediate_commonlog_android_cube_version_432e2392_00cc_4b69_a875_123160fbd374 -output hdfs://demo-online/kylin/kylin_metadata/kylin-d2084b99-942a-40e7-b692-1e895f4ed3dc/COMMONLOG_ANDROID_CUBE_VERSION/cuboid/ -input hdfs://demo-online/kylin/kylin_metadata/kylin-d2084b99-942a-40e7-b692-1e895f4ed3dc/kylin_intermediate_commonlog_android_cube_version_432e2392_00cc_4b69_a875_123160fbd374 -segmentId 432e2392-00cc-4b69-a875-123160fbd374 -metaUrl kylin_metadata@hdfs,path=hdfs://demo-online/kylin/kylin_metadata/kylin-d2084b99-942a-40e7-b692-1e895f4ed3dc/COMMONLOG_ANDROID_CUBE_VERSION/metadata -cubename COMMONLOG_ANDROID_CUBE_VERSION

**Comment by shaofengshi** [comment]
This project is out of date. Please send your question with logs to user@kylin.apache.org, before this you need join the group first. Check https://kylin.apache.org/community/
