### ISSUE TITLE
 ResourceStore error

### ISSUE THREAD

**Issue by JingpengZhang** [KylinOLAP/Kylin#97]
when i run deploy.sh ，there is an  error.  In source code i found this sentense
"static {
        knownImpl.add(HBaseResourceStore.class);
        knownImpl.add(FileResourceStore.class);
    }
"
and 
"
for (Class<? extends ResourceStore> cls : knownImpl) {

                try {
                    r = cls.getConstructor(KylinConfig.class).newInstance(kylinConfig);
" . when  FileResourceStore.getConstructor there is an error.

----------------------
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.kylinolap.common.persistence.ResourceStore.getStore(ResourceStore.java:66)
        at com.kylinolap.cube.CubeManager.getStore(CubeManager.java:640)
        at com.kylinolap.cube.CubeManager.loadAllCubeInstance(CubeManager.java:590)
        at com.kylinolap.cube.CubeManager.<init>(CubeManager.java:118)
        at com.kylinolap.cube.CubeManager.getInstance(CubeManager.java:83)
        at com.kylinolap.job.SampleCubeSetupTest.after(SampleCubeSetupTest.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.IllegalArgumentException: File not exist by 'kylin_metadata_qa@hbase:sjs_53_225:2181:/hbase': /home/imeda/zhangjp/Kylin/job/kylin_metadata_qa@hbase:sjs_53_225:2181:/hbase

**Comment by kiritisai** [comment]
What happened to this issue? Has it been resolved? Because, I'm facing a similar error while using Kylin in EMR.

**Comment by binmahone** [comment]
@kiritisai , the previous users failed because "Caused by: java.net.UnknownHostException: yarncluster" please find your root cause. 

Please prefer to use kylin mail list

**Comment by cd0409** [comment]
i have some probelm,please help me...i have run the check-env.sh,it's ok ,then i start the kylin ,but i can not access to the kylin web...hope to get the response from you

**Comment by binmahone** [comment]
please use mail list instead http://kylin.apache.org/community/

**Comment by zengzhaozheng** [comment]
In 1.5.1 version,i have the smae probelm.  "Caused by: java.lang.IllegalArgumentException: Failed to find metadata store by url: kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase"
I have confirmed that the znode "/hbase"  exist, and the znodes that i use in version0.7 is OK.
Any guys has ideas?

**Comment by zengzhaozheng** [comment]
kylin.log detail:

2016-04-18 10:16:36,780 INFO  [localhost-startStop-1] config.SecurityNamespaceHandler:59 : Spring Security 'config' module version is 3.1.2.RELEASE
2016-04-18 10:16:36,806 INFO  [localhost-startStop-1] method.GlobalMethodSecurityBeanDefinitionParser:141 : Using bean 'expressionHandler' as method ExpressionHandler implementation
2016-04-18 10:16:36,868 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'permitAll' for /api/user/authentication*/**
2016-04-18 10:16:36,868 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'isAuthenticated()' for /api/query*/**
2016-04-18 10:16:36,869 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'isAuthenticated()' for /api/metadata*/**
2016-04-18 10:16:36,869 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'permitAll' for /api/**/metrics
2016-04-18 10:16:36,869 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'permitAll' for /api/cache*/**
2016-04-18 10:16:36,870 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'hasAnyRole('ROLE_ANALYST')' for /api/cubes/src/tables
2016-04-18 10:16:36,870 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'isAuthenticated()' for /api/cubes*/**
2016-04-18 10:16:36,870 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'isAuthenticated()' for /api/models*/**
2016-04-18 10:16:36,870 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'isAuthenticated()' for /api/streaming*/**
2016-04-18 10:16:36,871 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'isAuthenticated()' for /api/job*/**
2016-04-18 10:16:36,871 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'permitAll' for /api/admin/config
2016-04-18 10:16:36,871 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'permitAll' for /api/projects
2016-04-18 10:16:36,872 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'hasRole('ROLE_ADMIN')' for /api/admin*/**
2016-04-18 10:16:36,873 INFO  [localhost-startStop-1] http.FilterInvocationSecurityMetadataSourceParser:134 : Creating access control expression attribute 'isAuthenticated()' for /api/**
2016-04-18 10:16:36,894 INFO  [localhost-startStop-1] http.AuthenticationConfigBuilder:465 : No login page configured. The default internal one will be used. Use the 'login-page' attribute to set the URL of the login page.
2016-04-18 10:16:36,900 INFO  [localhost-startStop-1] http.HttpSecurityBeanDefinitionParser:264 : Checking sorted filter chain: [Root bean: class [org.springframework.security.web.context.SecurityContextPersistenceFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 300, Root bean: class [org.springframework.security.web.authentication.logout.LogoutFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 400, <org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0>, order = 800, Root bean: class [org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1000, Root bean: class [org.springframework.security.web.authentication.www.BasicAuthenticationFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1200, Root bean: class [org.springframework.security.web.savedrequest.RequestCacheAwareFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1300, Root bean: class [org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1400, Root bean: class [org.springframework.security.web.authentication.AnonymousAuthenticationFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1700, Root bean: class [org.springframework.security.web.session.SessionManagementFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1800, Root bean: class [org.springframework.security.web.access.ExceptionTranslationFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1900, <org.springframework.security.web.access.intercept.FilterSecurityInterceptor#0>, order = 2000]
2016-04-18 10:16:37,251 WARN  [localhost-startStop-1] common.KylinConfig:162 : KYLIN_CONF property was not set, will seek KYLIN_HOME env variable
2016-04-18 10:16:37,324 INFO  [localhost-startStop-1] security.PasswordPlaceholderConfigurer:177 : Loading properties file from resource loaded through InputStream
2016-04-18 10:16:38,048 INFO  [localhost-startStop-1] util.Version:27 : HV000001: Hibernate Validator 5.1.3.Final
2016-04-18 10:16:39,182 INFO  [localhost-startStop-1] init.InitialTaskManager:36 : Kylin service is starting.....
2016-04-18 10:16:39,684 INFO  [localhost-startStop-1] controller.JobController:83 : Initializing Job Engine ....
2016-04-18 10:16:39,696 INFO  [Thread-3] manager.ExecutableManager:73 : Using metadata url: kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
2016-04-18 10:16:39,708 INFO  [Thread-3] dao.ExecutableDao:65 : Using metadata url: kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
2016-04-18 10:16:39,735 INFO  [Thread-3] persistence.ResourceStore:82 : Using metadata url kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase for resource store
2016-04-18 10:16:39,991 ERROR [Thread-3] persistence.ResourceStore:91 : Create new store instance failed
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.kylin.common.persistence.ResourceStore.createResourceStore(ResourceStore.java:85)
        at org.apache.kylin.common.persistence.ResourceStore.getStore(ResourceStore.java:104)
        at org.apache.kylin.metadata.MetadataManager.getStore(MetadataManager.java:139)
        at org.apache.kylin.metadata.MetadataManager.reloadAllSourceTable(MetadataManager.java:314)
        at org.apache.kylin.metadata.MetadataManager.init(MetadataManager.java:248)
        at org.apache.kylin.metadata.MetadataManager.<init>(MetadataManager.java:118)
        at org.apache.kylin.metadata.MetadataManager.getInstance(MetadataManager.java:88)
        at org.apache.kylin.job.dao.ExecutableDao.<init>(ExecutableDao.java:66)
        at org.apache.kylin.job.dao.ExecutableDao.getInstance(ExecutableDao.java:56)
        at org.apache.kylin.job.manager.ExecutableManager.<init>(ExecutableManager.java:75)
        at org.apache.kylin.job.manager.ExecutableManager.getInstance(ExecutableManager.java:64)
        at org.apache.kylin.job.impl.threadpool.DefaultScheduler.init(DefaultScheduler.java:166)
        at org.apache.kylin.rest.controller.JobController$1.run(JobController.java:90)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException: File not exist by 'kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase': /data1/app/apache-kylin-1.5.1-bin/kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
        at org.apache.kylin.common.persistence.FileResourceStore.<init>(FileResourceStore.java:49)
        ... 18 more
                                                                                                                                                                                                                           592,2-9       70%
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException: File not exist by 'kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase': /data1/app/apache-kylin-1.5.1-bin/kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
        at org.apache.kylin.common.persistence.FileResourceStore.<init>(FileResourceStore.java:49)
        ... 58 more
2016-04-18 10:16:40,849 ERROR [localhost-startStop-1] persistence.ResourceStore:91 : Create new store instance failed
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.kylin.common.persistence.ResourceStore.createResourceStore(ResourceStore.java:85)
        at org.apache.kylin.common.persistence.ResourceStore.getStore(ResourceStore.java:104)
        at org.apache.kylin.cube.CubeManager.getStore(CubeManager.java:874)
        at org.apache.kylin.cube.CubeManager.loadAllCubeInstance(CubeManager.java:808)
        at org.apache.kylin.cube.CubeManager.<init>(CubeManager.java:127)
        at org.apache.kylin.cube.CubeManager.getInstance(CubeManager.java:96)
        at org.apache.kylin.rest.service.CacheService.initCubeChangeListener(CacheService.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:346)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:299)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:132)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:394)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1448)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:876)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:818)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:735)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:478)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:284)
        
Caused by: java.lang.IllegalArgumentException: to use hbase storage, pls set 'kylin.storage.url=hbase' in kylin.properties
        at org.apache.kylin.storage.hbase.HBaseConnection.newHBaseConfiguration(HBaseConnection.java:88)
        at org.apache.kylin.storage.hbase.HBaseConnection.get(HBaseConnection.java:130)
        at org.apache.kylin.storage.hbase.HBaseResourceStore.getConnection(HBaseResourceStore.java:73)
        at org.apache.kylin.storage.hbase.HBaseResourceStore.createHTableIfNeeded(HBaseResourceStore.java:89)
        at org.apache.kylin.storage.hbase.HBaseResourceStore.<init>(HBaseResourceStore.java:85)
        ... 58 more
2016-04-18 10:16:40,867 ERROR [localhost-startStop-1] context.ContextLoader:307 : Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.apache.kylin.rest.service.CacheService org.apache.kylin.rest.controller.CacheController.cacheService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Failed to find metadata store by url: kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:287)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1106)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.apache.kylin.rest.service.CacheService org.apache.kylin.rest.controller.CacheController.cacheService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Failed to find metadata store by url: kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:506)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:284)
        ... 26 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Failed to find metadata store by url: kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:394)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1448)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:876)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:818)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:735)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:478)
        ... 28 more
Caused by: java.lang.IllegalArgumentException: Failed to find metadata store by url: kylin_metadata_qa@hbase:10.1.80.249:2181:/hbase,hbase:10.1.80.250:2181:/hbase,hbase:10.1.80.251:2181:/hbase
        at org.apache.kylin.common.persistence.ResourceStore.createResourceStore(ResourceStore.java:93)
        at org.apache.kylin.common.persistence.ResourceStore.getStore(ResourceStore.java:104)
        at org.apache.kylin.cube.CubeManager.getStore(CubeManager.java:874)
        at org.apache.kylin.cube.CubeManager.loadAllCubeInstance(CubeManager.java:808)
        at org.apache.kylin.cube.CubeManager.<init>(CubeManager.java:127)
        at org.apache.kylin.cube.CubeManager.getInstance(CubeManager.java:96)
        at org.apache.kylin.rest.service.CacheService.initCubeChangeListener(CacheService.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:346)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:299)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:132)
        ... 40 more

**Comment by liyang-gmt8** [comment]
Please move discussions to kylin mailing list on apache.

**Comment by venkateshmora23** [comment]
I have sent a similar error while I was trying to set up Kylin but I haven't heard back on the thread. 

Exception in thread "main" java.lang.IllegalArgumentException: Failed to find metadata store by url: kylin_metadata@hbase
	at org.apache.kylin.common.persistence.ResourceStore.createResourceStore(ResourceStore.java:99)
	at org.apache.kylin.common.persistence.ResourceStore.getStore(ResourceStore.java:111)
	at org.apache.kylin.rest.service.AclTableMigrationTool.checkIfNeedMigrate(AclTableMigrationTool.java:99)
	at org.apache.kylin.tool.AclTableMigrationCLI.main(AclTableMigrationCLI.java:43)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.kylin.common.persistence.ResourceStore.createResourceStore(ResourceStore.java:92)
	... 3 more
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the location for replica 0
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:372)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:153)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:58)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:219)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:275)
	at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:436)
	at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:310)
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:640)
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:367)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:411)
	at org.apache.kylin.storage.hbase.HBaseConnection.tableExists(HBaseConnection.java:280)
	at org.apache.kylin.storage.hbase.HBaseConnection.createHTableIfNeeded(HBaseConnection.java:305)
	at org.apache.kylin.storage.hbase.HBaseResourceStore.createHTableIfNeeded(HBaseResourceStore.java:114)
	at org.apache.kylin.storage.hbase.HBaseResourceStore.<init>(HBaseResourceStore.java:88)
